; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
        madhephaestus/ESP32Servo
        stempedia/DabbleESP32@1.5.1
monitor_speed = 115200

; ---------- CH?N CODE Ð? N?P VÀO ESP32 ----------
; Hu?ng d?n: B? ghi chú (xóa d?u ch?m ph?y ;) ? dòng b?n mu?n dùng, 
; và thêm d?u ; vào dòng b?n không mu?n dùng.

; L?a ch?n 1: N?p file code ÐI?U KHI?N TH? CÔNG:
build_src_filter = +<*> -<dieu_khien_tu_dong.cpp>

; L?a ch?n 2: N?p file code ÐI?U KHI?N T? Ð?NG:
; build_src_filter = +<*> -<dieu_khien_thu_cong.cpp>
; ------------------------------------------------
